# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Chart
                                 A QGIS plugin
 qml chart
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-01-16
        copyright            : (C) 2019 by Oslandia
        email                : julien.cabieces@oslandia.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Chart class from file Chart.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .chart import Chart
    return Chart(iface)
